-- 코드를 입력하세요
SELECT ANIMAL_ID, NAME
FROM (
    SELECT a.ANIMAL_ID, a.NAME, b.DATETIME - a.DATETIME AS DURATION
    FROM ANIMAL_INS a INNER JOIN ANIMAL_OUTS b on a.ANIMAL_ID = b.ANIMAL_ID
    ORDER BY DURATION DESC
)
WHERE ROWNUM <= 2;