-- 코드를 입력하세요
SELECT a.WRITER_ID, b.NICKNAME, (b.CITY || ' ' || b.STREET_ADDRESS1 || ' ' || b.STREET_ADDRESS2) AS 전체주소, 
CASE WHEN LENGTH(b.TLNO) = 11 THEN SUBSTR(TLNO, 0,3) || '-' || SUBSTR(TLNO,4,4)|| '-' || SUBSTR(TLNO,8,4)
END AS 전화번호
FROM (
SELECT WRITER_ID, COUNT(*)
FROM USED_GOODS_BOARD
GROUP BY WRITER_ID
HAVING COUNT(*) >= 3
) a INNER JOIN USED_GOODS_USER b on a.WRITER_ID = b.USER_ID
ORDER BY a.WRITER_ID DESC;