-- 코드를 입력하세요
SELECT a.CATEGORY, SUM(b.SALES) AS TOTAL_SALES
FROM BOOK a
INNER JOIN BOOK_SALES b on a.BOOK_ID = b.BOOK_ID
WHERE TO_CHAR(b.SALES_DATE, 'YYYY-MM') = '2022-01'
GROUP BY a.CATEGORY
ORDER BY a.CATEGORY;